services:
  db:
    image: postgres:16-alpine
    container_name: folio-db-prod
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${DB_USER:-folio_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-folio_db}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-folio_user} -d ${DB_NAME:-folio_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - folio-network
    restart: unless-stopped

  api:
    image: ghcr.io/${GITHUB_REPOSITORY}/folio-backend:latest
    container_name: folio-api-prod
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: ${DB_USER:-folio_user}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME:-folio_db}
      SERVER_PORT: 8080
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_REDIRECT_URL: ${GOOGLE_REDIRECT_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_BOOKS_API_KEY: ${GOOGLE_BOOKS_API_KEY}
    networks:
      - folio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    image: ghcr.io/${GITHUB_REPOSITORY}/folio-frontend:latest
    container_name: folio-frontend-prod
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - folio-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  folio-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
