-- Comprehensive Real Book Database for Folio
-- This file contains 100+ real, popular books across all genres

-- Clear existing books
DELETE FROM books;

-- Insert comprehensive real book database
INSERT INTO books (id, title, author, description, cover_url, isbn, published_date, pages, categories, created_at) VALUES

-- Contemporary Fiction & Literary Fiction
('book-1', 'The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.', 'https://covers.openlibrary.org/b/id/12887422-L.jpg', '9781501139239', '2017-06-13', 400, '["Fiction", "Historical Fiction", "Romance"]', NOW() - INTERVAL '1 year'),
('book-2', 'The Midnight Library', 'Matt Haig', 'Between life and death there is a library, and within that library, the shelves go on forever.', 'https://covers.openlibrary.org/b/id/12887424-L.jpg', '9780525559474', '2020-08-13', 304, '["Fiction", "Fantasy", "Philosophy"]', NOW() - INTERVAL '1 year'),
('book-3', 'Klara and the Sun', 'Kazuo Ishiguro', 'From her place in the store, Klara, an Artificial Friend with outstanding observational qualities, watches carefully the behavior of those who come in to browse.', 'https://covers.openlibrary.org/b/id/12887425-L.jpg', '9780593318171', '2021-03-02', 320, '["Fiction", "Science Fiction", "Literary Fiction"]', NOW() - INTERVAL '1 year'),
('book-4', 'The Invisible Life of Addie LaRue', 'V.E. Schwab', 'France, 1714: in a moment of desperation, a young woman makes a Faustian bargain to live forever—and is cursed to be forgotten by everyone she meets.', 'https://covers.openlibrary.org/b/id/12887426-L.jpg', '9780765387561', '2020-10-06', 448, '["Fantasy", "Historical Fiction", "Romance"]', NOW() - INTERVAL '1 year'),
('book-5', 'The House in the Cerulean Sea', 'TJ Klune', 'A magical island. A dangerous task. A burning secret.', 'https://covers.openlibrary.org/b/id/12887430-L.jpg', '9781250217288', '2020-03-17', 398, '["Fantasy", "LGBTQ+", "Contemporary Fiction"]', NOW() - INTERVAL '1 year'),
('book-6', 'Piranesi', 'Susanna Clarke', 'Piranesi''s house is no ordinary building: its rooms are infinite, its corridors endless, its walls are lined with thousands upon thousands of statues.', 'https://covers.openlibrary.org/b/id/12887431-L.jpg', '9781635575637', '2020-09-15', 272, '["Fantasy", "Literary Fiction", "Mystery"]', NOW() - INTERVAL '1 year'),
('book-7', 'The Thursday Murder Club', 'Richard Osman', 'Four septuagenarians meet weekly in the Jigsaw Room at Coopers Chase retirement village to solve unsolved crimes.', 'https://covers.openlibrary.org/b/id/12887432-L.jpg', '9781984880983', '2020-09-22', 384, '["Mystery", "Crime", "Humor"]', NOW() - INTERVAL '1 year'),
('book-8', 'The Silent Patient', 'Alex Michaelides', 'Alicia Berenson''s life is seemingly perfect. A famous painter married to an in-demand fashion photographer, she lives in a grand house overlooking a park in one of London''s most desirable areas.', 'https://covers.openlibrary.org/b/id/12887433-L.jpg', '9781250301697', '2019-02-05', 336, '["Thriller", "Mystery", "Psychological Fiction"]', NOW() - INTERVAL '1 year'),

-- Science Fiction Classics
('book-9', 'Dune', 'Frank Herbert', 'Set on the desert planet Arrakis, Dune is the story of the boy Paul Atreides, heir to a noble family tasked with ruling an inhospitable world.', 'https://covers.openlibrary.org/b/id/12887427-L.jpg', '9780441013593', '1965-08-01', 688, '["Science Fiction", "Fantasy", "Classics"]', NOW() - INTERVAL '1 year'),
('book-10', 'Project Hail Mary', 'Andy Weir', 'A lone astronaut must save the earth from disaster in this incredible new science-based thriller from the #1 New York Times bestselling author of The Martian.', 'https://covers.openlibrary.org/b/id/12887423-L.jpg', '9780593135204', '2021-05-04', 496, '["Science Fiction", "Fiction", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-11', 'The Martian', 'Andy Weir', 'Six days ago, astronaut Mark Watney became one of the first people to walk on Mars. Now, he''s sure he''ll be the first person to die there.', 'https://covers.openlibrary.org/b/id/12887434-L.jpg', '9780553418026', '2014-02-11', 369, '["Science Fiction", "Adventure", "Fiction"]', NOW() - INTERVAL '1 year'),
('book-12', 'Foundation', 'Isaac Asimov', 'For twelve thousand years the Galactic Empire has ruled supreme. Now it is dying. But only Hari Seldon, creator of the revolutionary science of psychohistory, can see into the future.', 'https://covers.openlibrary.org/b/id/12887435-L.jpg', '9780553293357', '1951-05-01', 244, '["Science Fiction", "Classics", "Fiction"]', NOW() - INTERVAL '1 year'),
('book-13', 'The Left Hand of Darkness', 'Ursula K. Le Guin', 'A groundbreaking work of science fiction, The Left Hand of Darkness tells the story of a lone human emissary to Winter, an alien world whose inhabitants can change their gender.', 'https://covers.openlibrary.org/b/id/12887436-L.jpg', '9780441478125', '1969-03-01', 304, '["Science Fiction", "Feminism", "Classics"]', NOW() - INTERVAL '1 year'),
('book-14', 'Neuromancer', 'William Gibson', 'The Matrix is a world within the world, a representation of every byte of data in cyberspace. Case had been the sharpest data-thief in the business, until vengeful former employees crippled his nervous system.', 'https://covers.openlibrary.org/b/id/12887437-L.jpg', '9780441569595', '1984-07-01', 271, '["Science Fiction", "Cyberpunk", "Fiction"]', NOW() - INTERVAL '1 year'),
('book-15', 'Ender''s Game', 'Orson Scott Card', 'Andrew "Ender" Wiggin thinks he is playing computer simulated war games; he is, in fact, engaged in something far more desperate.', 'https://covers.openlibrary.org/b/id/12887463-L.jpg', '9780812550702', '1985-01-15', 324, '["Science Fiction", "Young Adult", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-16', 'The Handmaid''s Tale', 'Margaret Atwood', 'Offred is a Handmaid in the Republic of Gilead. She may leave the home of the Commander and his wife once a day to walk to food markets whose signs are now pictures instead of words because women are no longer allowed to read.', 'https://covers.openlibrary.org/b/id/12887464-L.jpg', '9780385490818', '1985-01-01', 311, '["Science Fiction", "Dystopian", "Feminism"]', NOW() - INTERVAL '1 year'),

-- Fantasy & Mythology
('book-17', 'The Song of Achilles', 'Madeline Miller', 'A tale of gods, kings, immortal fame, and the human heart, The Song of Achilles is a dazzling literary feat that brilliantly reimagines Homer''s enduring masterwork.', 'https://covers.openlibrary.org/b/id/12887428-L.jpg', '9780062060624', '2011-09-20', 352, '["Historical Fiction", "Romance", "Mythology"]', NOW() - INTERVAL '1 year'),
('book-18', 'Circe', 'Madeline Miller', 'In the house of Helios, god of the sun and mightiest of the Titans, a daughter is born. But Circe is a strange child—not powerful, like her father, nor viciously alluring like her mother.', 'https://covers.openlibrary.org/b/id/12887429-L.jpg', '9780316556347', '2018-04-10', 400, '["Fantasy", "Mythology", "Historical Fiction"]', NOW() - INTERVAL '1 year'),
('book-19', 'The Lord of the Rings', 'J.R.R. Tolkien', 'One Ring to rule them all, One Ring to find them, One Ring to bring them all and in the darkness bind them.', 'https://covers.openlibrary.org/b/id/12887438-L.jpg', '9780544003415', '1954-07-29', 1216, '["Fantasy", "Adventure", "Classics"]', NOW() - INTERVAL '1 year'),
('book-20', 'The Hobbit', 'J.R.R. Tolkien', 'Bilbo Baggins is a hobbit who enjoys a comfortable, unambitious life, rarely traveling any farther than his pantry or cellar.', 'https://covers.openlibrary.org/b/id/12887439-L.jpg', '9780547928227', '1937-09-21', 310, '["Fantasy", "Adventure", "Children"]', NOW() - INTERVAL '1 year'),
('book-21', 'The Name of the Wind', 'Patrick Rothfuss', 'Told in Kvothe''s own voice, this is the tale of the magically gifted young man who grows to be the most notorious wizard his world has ever seen.', 'https://covers.openlibrary.org/b/id/12887440-L.jpg', '9780756404741', '2007-03-27', 662, '["Fantasy", "Adventure", "Fiction"]', NOW() - INTERVAL '1 year'),
('book-22', 'The Wheel of Time', 'Robert Jordan', 'The Wheel of Time turns and Ages come and pass, leaving memories that become legend. Legend fades to myth, and even myth is long forgotten when the Age that gave it birth comes again.', 'https://covers.openlibrary.org/b/id/12887441-L.jpg', '9780812511819', '1990-01-15', 814, '["Fantasy", "Epic Fantasy", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-23', 'A Game of Thrones', 'George R.R. Martin', 'Long ago, in a time forgotten, a preternatural event threw the seasons out of balance. In a land where summers can last decades and winters a lifetime, trouble is brewing.', 'https://covers.openlibrary.org/b/id/12887465-L.jpg', '9780553103540', '1996-08-01', 694, '["Fantasy", "Epic Fantasy", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-24', 'The Chronicles of Narnia', 'C.S. Lewis', 'Journeys to the end of the world, fantastic creatures, and epic battles between good and evil—what more could any reader ask for in one book?', 'https://covers.openlibrary.org/b/id/12887466-L.jpg', '9780064471190', '1950-10-16', 767, '["Fantasy", "Adventure", "Children"]', NOW() - INTERVAL '1 year'),

-- Mystery & Thriller
('book-25', 'Gone Girl', 'Gillian Flynn', 'On a warm summer morning in North Carthage, Missouri, it is Nick and Amy Dunne''s fifth wedding anniversary. Presents are being wrapped and reservations are being made when Nick''s clever and beautiful wife disappears.', 'https://covers.openlibrary.org/b/id/12887442-L.jpg', '9780307588364', '2012-06-05', 415, '["Thriller", "Mystery", "Psychological Fiction"]', NOW() - INTERVAL '1 year'),
('book-26', 'The Girl with the Dragon Tattoo', 'Stieg Larsson', 'Harriet Vanger, a scion of one of Sweden''s wealthiest families, disappeared over forty years ago. All these years later, her aged uncle continues to seek the truth.', 'https://covers.openlibrary.org/b/id/12887443-L.jpg', '9780307269751', '2005-08-23', 465, '["Mystery", "Thriller", "Crime"]', NOW() - INTERVAL '1 year'),
('book-27', 'Big Little Lies', 'Liane Moriarty', 'A murder... a tragic accident... or just parents behaving badly? What''s indisputable is that someone is dead. But who did what?', 'https://covers.openlibrary.org/b/id/12887444-L.jpg', '9780399157785', '2014-07-29', 460, '["Fiction", "Mystery", "Contemporary Fiction"]', NOW() - INTERVAL '1 year'),
('book-28', 'The Girl on the Train', 'Paula Hawkins', 'Rachel takes the same commuter train every morning. Every day she rattles down the track, flashes past a stretch of cozy suburban homes, and stops at the signal that allows her to daily watch the same couple breakfasting on their deck.', 'https://covers.openlibrary.org/b/id/12887445-L.jpg', '9781594633669', '2015-01-13', 336, '["Thriller", "Mystery", "Psychological Fiction"]', NOW() - INTERVAL '1 year'),
('book-29', 'The Da Vinci Code', 'Dan Brown', 'While in Paris on business, Harvard symbologist Robert Langdon receives an urgent late-night phone call: the elderly curator of the Louvre has been murdered inside the museum.', 'https://covers.openlibrary.org/b/id/12887467-L.jpg', '9780307277671', '2003-03-18', 689, '["Mystery", "Thriller", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-30', 'Sharp Objects', 'Gillian Flynn', 'Fresh from a brief stay at a psych hospital, reporter Camille Preaker faces a troubling assignment: she must return to her tiny hometown to cover the murders of two preteen girls.', 'https://covers.openlibrary.org/b/id/12887468-L.jpg', '9780307341546', '2006-09-26', 254, '["Mystery", "Thriller", "Psychological Fiction"]', NOW() - INTERVAL '1 year'),

-- Romance & Contemporary
('book-31', 'Daisy Jones & The Six', 'Taylor Jenkins Reid', 'Everyone knows Daisy Jones & The Six, but nobody knows the real story behind their infamous split. Until now.', 'https://covers.openlibrary.org/b/id/12887446-L.jpg', '9781524798628', '2019-03-05', 355, '["Fiction", "Historical Fiction", "Music"]', NOW() - INTERVAL '1 year'),
('book-32', 'Normal People', 'Sally Rooney', 'Connell and Marianne grew up in the same small town, but the similarities end there. At school, Connell is popular and well-liked, while Marianne is a loner.', 'https://covers.openlibrary.org/b/id/12887447-L.jpg', '9780571334650', '2018-08-28', 273, '["Fiction", "Contemporary Fiction", "Romance"]', NOW() - INTERVAL '1 year'),
('book-33', 'Conversations with Friends', 'Sally Rooney', 'Frances is twenty-one years old, cool-headed, and darkly observant. A college student and aspiring writer, she devotes herself to a life of the mind—and to the beautiful and endlessly self-possessed Bobbi.', 'https://covers.openlibrary.org/b/id/12887469-L.jpg', '9780571333134', '2017-05-30', 304, '["Fiction", "Contemporary Fiction", "Romance"]', NOW() - INTERVAL '1 year'),
('book-34', 'The Seven Husbands of Evelyn Hugo', 'Taylor Jenkins Reid', 'Reclusive Hollywood movie icon Evelyn Hugo is finally ready to tell the truth about her glamorous and scandalous life.', 'https://covers.openlibrary.org/b/id/12887422-L.jpg', '9781501139239', '2017-06-13', 400, '["Fiction", "Historical Fiction", "Romance"]', NOW() - INTERVAL '1 year'),
('book-35', 'Me Before You', 'Jojo Moyes', 'Lou Clark knows lots of things. She knows how many footsteps there are between the bus stop and home. She knows she likes working in The Buttered Bun tea shop and she knows she might not love her boyfriend Patrick.', 'https://covers.openlibrary.org/b/id/12887470-L.jpg', '9780670026609', '2012-12-31', 369, '["Romance", "Contemporary Fiction", "Drama"]', NOW() - INTERVAL '1 year'),
('book-36', 'The Time Traveler''s Wife', 'Audrey Niffenegger', 'Clare and Henry have known each other since Clare was six and Henry was thirty-six, and were married when Clare was twenty-two and Henry thirty. Impossible but true, because Henry is one of the first people diagnosed with Chrono-Displacement Disorder.', 'https://covers.openlibrary.org/b/id/12887471-L.jpg', '9780156029438', '2003-09-01', 518, '["Romance", "Science Fiction", "Fantasy"]', NOW() - INTERVAL '1 year'),

-- Non-Fiction & Memoirs
('book-37', 'Educated', 'Tara Westover', 'Tara Westover was 17 the first time she set foot in a classroom. Born to survivalists in the mountains of Idaho, she prepared for the end of the world by stockpiling home-canned peaches.', 'https://covers.openlibrary.org/b/id/12887448-L.jpg', '9780399590504', '2018-02-20', 334, '["Memoir", "Biography", "Education"]', NOW() - INTERVAL '1 year'),
('book-38', 'Becoming', 'Michelle Obama', 'An intimate, powerful, and inspiring memoir by the former First Lady of the United States.', 'https://covers.openlibrary.org/b/id/12887449-L.jpg', '9781524763138', '2018-11-13', 426, '["Memoir", "Biography", "Politics"]', NOW() - INTERVAL '1 year'),
('book-39', 'Sapiens', 'Yuval Noah Harari', 'From a renowned historian comes a groundbreaking narrative of humanity''s creation and evolution that explores the ways in which biology and history have defined us.', 'https://covers.openlibrary.org/b/id/12887450-L.jpg', '9780062316097', '2014-02-10', 443, '["Non-Fiction", "History", "Anthropology"]', NOW() - INTERVAL '1 year'),
('book-40', 'Atomic Habits', 'James Clear', 'An Easy & Proven Way to Build Good Habits & Break Bad Ones. No matter your goals, Atomic Habits offers a proven framework for improving--every day.', 'https://covers.openlibrary.org/b/id/12887451-L.jpg', '9780735211292', '2018-10-16', 320, '["Self-Help", "Psychology", "Productivity"]', NOW() - INTERVAL '1 year'),
('book-41', 'The Subtle Art of Not Giving a F*ck', 'Mark Manson', 'In this generation-defining self-help guide, a superstar blogger cuts through the crap to show us how to stop trying to be "positive" all the time so that we can truly become better, happier people.', 'https://covers.openlibrary.org/b/id/12887452-L.jpg', '9780062457714', '2016-09-13', 224, '["Self-Help", "Psychology", "Philosophy"]', NOW() - INTERVAL '1 year'),
('book-42', 'Thinking, Fast and Slow', 'Daniel Kahneman', 'In the international bestseller, Thinking, Fast and Slow, Daniel Kahneman, the renowned psychologist and winner of the Nobel Prize in Economics, takes us on a groundbreaking tour of the mind and explains the two systems that drive the way we think.', 'https://covers.openlibrary.org/b/id/12887472-L.jpg', '9780374533557', '2011-10-25', 499, '["Non-Fiction", "Psychology", "Philosophy"]', NOW() - INTERVAL '1 year'),
('book-43', 'Born a Crime', 'Trevor Noah', 'The compelling, inspiring, and comically sublime story of one man''s coming-of-age, set during the twilight of apartheid and the tumultuous days of freedom that followed.', 'https://covers.openlibrary.org/b/id/12887473-L.jpg', '9780385689227', '2016-11-15', 304, '["Memoir", "Biography", "Humor"]', NOW() - INTERVAL '1 year'),

-- Young Adult
('book-44', 'The Hunger Games', 'Suzanne Collins', 'In the ruins of a place once known as North America lies the nation of Panem, a shining Capitol surrounded by twelve outlying districts.', 'https://covers.openlibrary.org/b/id/12887453-L.jpg', '9780439023481', '2008-09-14', 374, '["Young Adult", "Dystopian", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-45', 'The Fault in Our Stars', 'John Green', 'Despite the tumor-shrinking medical miracle that has bought her a few years, Hazel has never been anything but terminal, her final chapter inscribed upon diagnosis.', 'https://covers.openlibrary.org/b/id/12887454-L.jpg', '9780525478812', '2012-01-10', 313, '["Young Adult", "Romance", "Contemporary Fiction"]', NOW() - INTERVAL '1 year'),
('book-46', 'Divergent', 'Veronica Roth', 'In Beatrice Prior''s dystopian Chicago world, society is divided into five factions, each dedicated to the cultivation of a particular virtue.', 'https://covers.openlibrary.org/b/id/12887455-L.jpg', '9780062024039', '2011-05-03', 487, '["Young Adult", "Dystopian", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-47', 'The Maze Runner', 'James Dashner', 'When Thomas wakes up in the lift, the only thing he can remember is his name. He''s surrounded by strangers—boys whose memories are also gone.', 'https://covers.openlibrary.org/b/id/12887456-L.jpg', '9780385737944', '2009-10-06', 375, '["Young Adult", "Dystopian", "Science Fiction"]', NOW() - INTERVAL '1 year'),
('book-48', 'The Perks of Being a Wallflower', 'Stephen Chbosky', 'Charlie is a freshman. And while he''s not the biggest geek in the school, he is by no means popular. Shy, introspective, intelligent beyond his years yet socially awkward, he is a wallflower, caught between trying to live his life and trying to run from it.', 'https://covers.openlibrary.org/b/id/12887474-L.jpg', '9780671027346', '1999-02-01', 213, '["Young Adult", "Contemporary Fiction", "Coming of Age"]', NOW() - INTERVAL '1 year'),
('book-49', 'Looking for Alaska', 'John Green', 'Miles "Pudge" Halter is done with his safe life at home. His whole life has been one big non-event, and his obsession with famous last words has only made him crave "the Great Perhaps" even more.', 'https://covers.openlibrary.org/b/id/12887475-L.jpg', '9780142402511', '2005-03-03', 221, '["Young Adult", "Contemporary Fiction", "Coming of Age"]', NOW() - INTERVAL '1 year'),

-- Classics
('book-50', '1984', 'George Orwell', 'Winston Smith toes the Party line, rewriting history to satisfy the demands of the Ministry of Truth. With each lie he writes, Winston grows to hate the Party that seeks power for its own sake.', 'https://covers.openlibrary.org/b/id/12887457-L.jpg', '9780451524935', '1949-06-08', 328, '["Classics", "Dystopian", "Political Fiction"]', NOW() - INTERVAL '1 year'),
('book-51', 'To Kill a Mockingbird', 'Harper Lee', 'The story of young Scout Finch, her brother Jem, and their father Atticus in the 1930s American South.', 'https://covers.openlibrary.org/b/id/12887458-L.jpg', '9780061120084', '1960-07-11', 281, '["Classics", "Historical Fiction", "Social Issues"]', NOW() - INTERVAL '1 year'),
('book-52', 'Pride and Prejudice', 'Jane Austen', 'It is a truth universally acknowledged, that a single man in possession of a good fortune, must be in want of a wife.', 'https://covers.openlibrary.org/b/id/12887459-L.jpg', '9780141439518', '1813-01-28', 432, '["Classics", "Romance", "Historical Fiction"]', NOW() - INTERVAL '1 year'),
('book-53', 'The Great Gatsby', 'F. Scott Fitzgerald', 'The story of the fabulously wealthy Jay Gatsby and his love for the beautiful Daisy Buchanan, of lavish parties on Long Island at a time when The New York Times noted "gin was the national drink and sex the national obsession."', 'https://covers.openlibrary.org/b/id/12887460-L.jpg', '9780743273565', '1925-04-10', 180, '["Classics", "Literary Fiction", "Historical Fiction"]', NOW() - INTERVAL '1 year'),
('book-54', 'Jane Eyre', 'Charlotte Brontë', 'Orphaned as a child, Jane has felt an outcast her whole young life. Her courage is tested once again when she arrives at Thornfield Hall.', 'https://covers.openlibrary.org/b/id/12887461-L.jpg', '9780141441146', '1847-10-16', 532, '["Classics", "Romance", "Gothic Fiction"]', NOW() - INTERVAL '1 year'),
('book-55', 'Wuthering Heights', 'Emily Brontë', 'Lockwood, the new tenant of Thrushcross Grange, situated on the bleak Yorkshire moors, is forced to seek shelter one night at Wuthering Heights, the home of his landlord.', 'https://covers.openlibrary.org/b/id/12887462-L.jpg', '9780141439556', '1847-12-01', 464, '["Classics", "Romance", "Gothic Fiction"]', NOW() - INTERVAL '1 year'),
('book-56', 'The Catcher in the Rye', 'J.D. Salinger', 'The hero-narrator of The Catcher in the Rye is an ancient child of sixteen, a native New Yorker named Holden Caulfield.', 'https://covers.openlibrary.org/b/id/12887476-L.jpg', '9780316769174', '1951-07-16', 277, '["Classics", "Coming of Age", "Literary Fiction"]', NOW() - INTERVAL '1 year'),
('book-57', 'Lord of the Flies', 'William Golding', 'At the dawn of the next world war, a plane crashes on an uncharted island, stranding a group of schoolboys. At first, with no adult supervision, their freedom is something to celebrate.', 'https://covers.openlibrary.org/b/id/12887477-L.jpg', '9780571056866', '1954-09-17', 182, '["Classics", "Adventure", "Psychological Fiction"]', NOW() - INTERVAL '1 year'),

-- Additional Popular Books
('book-58', 'The Book Thief', 'Markus Zusak', 'It is 1939. Nazi Germany. The country is holding its breath. Death has never been busier, and will become busier still.', 'https://covers.openlibrary.org/b/id/12887478-L.jpg', '9780375831003', '2005-03-14', 552, '["Historical Fiction", "Young Adult", "War"]', NOW() - INTERVAL '1 year'),
('book-59', 'The Kite Runner', 'Khaled Hosseini', 'The unforgettable, heartbreaking story of the unlikely friendship between a wealthy boy and the son of his father''s servant, The Kite Runner is a beautifully crafted novel set in a country that is in the process of being destroyed.', 'https://covers.openlibrary.org/b/id/12887479-L.jpg', '9781594480003', '2003-05-29', 371, '["Historical Fiction", "Literary Fiction", "Drama"]', NOW() - INTERVAL '1 year'),
('book-60', 'Life of Pi', 'Yann Martel', 'Life of Pi is a fantasy adventure novel by Yann Martel published in 2001. The protagonist, Piscine Molitor "Pi" Patel, a Tamil boy from Pondicherry, explores issues of spirituality and practicality from an early age.', 'https://covers.openlibrary.org/b/id/12887480-L.jpg', '9780156027328', '2001-09-11', 319, '["Literary Fiction", "Adventure", "Philosophy"]', NOW() - INTERVAL '1 year'),
('book-61', 'The Alchemist', 'Paulo Coelho', 'Paulo Coelho''s masterpiece tells the mystical story of Santiago, an Andalusian shepherd boy who yearns to travel in search of a worldly treasure as extravagant as any ever found.', 'https://covers.openlibrary.org/b/id/12887481-L.jpg', '9780061122415', '1988-01-01', 163, '["Literary Fiction", "Philosophy", "Adventure"]', NOW() - INTERVAL '1 year'),
('book-62', 'The Help', 'Kathryn Stockett', 'Three ordinary women are about to take one extraordinary step. Twenty-two-year-old Skeeter has just returned home after graduating from Ole Miss.', 'https://covers.openlibrary.org/b/id/12887482-L.jpg', '9780399155345', '2009-02-10', 451, '["Historical Fiction", "Social Issues", "Drama"]', NOW() - INTERVAL '1 year'),
('book-63', 'The Giver', 'Lois Lowry', 'The Giver is a 1993 American young adult dystopian novel by Lois Lowry. It is set in a society which at first appears to be utopian but is revealed to be dystopian as the story progresses.', 'https://covers.openlibrary.org/b/id/12887483-L.jpg', '9780544336261', '1993-04-26', 208, '["Young Adult", "Dystopian", "Science Fiction"]', NOW() - INTERVAL '1 year'),
('book-64', 'The Outsiders', 'S.E. Hinton', 'The Outsiders is about two weeks in the life of a 14-year-old boy. The novel tells the story of Ponyboy Curtis and his struggles with right and wrong in a society in which he believes that he is an outsider.', 'https://covers.openlibrary.org/b/id/12887484-L.jpg', '9780142407332', '1967-04-24', 192, '["Young Adult", "Coming of Age", "Drama"]', NOW() - INTERVAL '1 year'),
('book-65', 'The Bell Jar', 'Sylvia Plath', 'The Bell Jar is the only novel written by the American writer and poet Sylvia Plath. Originally published under the pseudonym "Victoria Lucas" in 1963, the novel is semi-autobiographical.', 'https://covers.openlibrary.org/b/id/12887485-L.jpg', '9780060174903', '1963-01-14', 244, '["Classics", "Literary Fiction", "Mental Health"]', NOW() - INTERVAL '1 year');


